#!/bin/bash -e

# Run phpunit
vendor/bin/phpunit src/lib/EbayEnterprise/Dom "$@" # This argument list should usually be empty, but can be switched to --debug or other flags for quick checks. Such as when phpunit suddenly starts segfaulting on Jenkins.
