#!/bin/bash -e

##
# Set up ecomdev testing for Mage Log
#

# Set up the Magento 'webroot' in the 'build' directory.
mkdir -p build

# Set up the phpunit configurations
cp tests/phpunit.xml.dist .

# Run phpunit
phpunit src

